[package]
name = "rust-wasm"
version = "0.1.0"
authors = ["Yuki Ikegaya"]
description = "A sample project with wasm-pack"
license = "MIT/Apache-2.0"
repository = "https://github.com/ikeyu0806/rust-wasm"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
