version: '3.8'

services:
  wasm:
    build:
      context: .
    working_dir: /app/site
    command: sh -c "npx webpack && npm run serve"
    # デバッグ
    # command: ["tail", "-f", "/dev/null"]
    ports:
      - 3456:8080
    volumes:
      - .:/app      
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/target
      - cargo-bin:/usr/local/cargo/bin

volumes:
  cargo-cache:
  target-cache:
  cargo-bin:
